## Master script for Leo's plots, thesis edition

# load libraries
library(tidyverse)
library(readxl)
library(ComplexHeatmap)
library(circlize)
library(ggrepel)
library(PFun)
library(forcats)
library(FactoMineR) # for PCA
library(factoextra) # for PCA
library(here)
library(openxlsx)


# Set to custom clean theme
# theme_set(theme_PN(base_size = 12))
# scale_colour_discrete = ggthemes::scale_colour_tableau
# scale_fill_discrete = ggthemes::scale_fill_tableau

# set working directory to selected directory
# setwd("/Users/dmarti14/Documents/MRC_Postdoc/Projects/Leo/DATA_TO_PLOT")

# output directory
dir.create('Summary', showWarnings = TRUE, recursive = FALSE, mode = "0777")





#############################
### 4-way screen (biolog) ###
#############################


### Load data

info = read_csv('Biolog_metabolites.csv',quote = "\"")

info %>% filter(Plate == 'PM5')

# load bacterial data

data.b = read_csv('../Bacteria data/All_files/Data_Leo5/Summary.csv', quote = "\"") %>%
  rename(logAUC_raw = `750nm_f_logAUC`) %>% #`750nm_f_logAUC` data column is what we need for logAUC values
  mutate(Strain = as.character(Strain),
         Strain = recode(Strain, 'BW25113' = 'BW'), #Change strain namings
         ReplicateB = paste0('B', as.character(Replicate)), #Generate replicate ID which indicate that it's data for bacteria
         Type = ifelse(Type == 'Control','C','T'),
         Sample = paste(Strain, Type, sep = '_'),
         Type = factor(Type,
                     levels = c('C', 'T'),
                     labels = c('Control', 'Treatment')),
         Row = str_match_all(Well,'[:digit:]{1,}'), #Get plate row names from well name. 
         Col = str_match_all(Well,'[:alpha:]{1,}'), #Get plate column names from well name
         Row = factor(Row, levels = 1:12), #Make them categorical variable with set order them
         Col = factor(Col, levels = LETTERS[1:8]),
         SampleID = paste(Sample, Replicate, sep = '_'),
         Sample = as.factor(Sample),
         Strain = as.factor(Strain)) %>% #Change Type column coding
  group_by(Strain, Type, Plate, Replicate, Group) %>%
  mutate(logAUC = logAUC_raw - logAUC_raw[Metabolite == 'Negative Control']) %>% # Normalisation agains negative control in each plate
  select(SampleID, Sample, Strain, Type, Replicate, ReplicateB, Index, Plate, 
    Well, Row, Col, Metabolite, MetaboliteU, EcoCycID, KEGG_ID, Group, Class, logAUC_raw, logAUC) %>%
  ungroup 
  

# deleting replicate 3 of pyrE treatment (pyrE_T_3), Biospa failed to deliver data correctly 
data.b = data.b %>%
  filter(SampleID != "pyrE_T_3")


### Summary statistics
# Note: we do not use several of these variables for the plots, but could be useful
# They were generated by Pov 

bac.byrep = data.b %>%
  	unite(STR, Strain, Type, ReplicateB) %>% #Generete unique IDs by concatenating Strain, Type and Replicate values
  	# Select only the columns which are necessary: descriptions, values, exclude Replicate (Now it's ReplicateB), Comment, Reader
  	select(STR, Plate, Well, Row, Col, Index:Class,logAUC_raw, -Replicate) %>% 
  	spread(STR, logAUC_raw) #Spread values into a wide table



# Replicates per plate
data.breps = data.b %>%
  	group_by(Strain, Plate, Type) %>%
  	summarise(Replicates = n()/96)


# Generate summary statistics for each group
bac.sum = data.b %>%
  	group_by(Strain, Plate, Replicate, Group) %>%
  	gather(Measure, Value, logAUC_raw, logAUC) %>%
  	group_by(Measure, Strain, Type, Plate, Well, Index, Metabolite, MetaboliteU) %>% #Work on subsets based on selected grouping variables
  	summarise(Mean = mean(Value, na.rm = TRUE), # Do selected summary over group items - replicates, ignore missing values
            SD = sd(Value, na.rm = TRUE),
            SE = SD/sqrt(n())) %>% # standard error of the mean
  	ungroup %>%
  	mutate(PE = Mean+SE,
         NE = Mean-SE)



# With additional info
bac.sum2 = data.b %>%
  filter(Strain == 'BW' & Plate %in% c('PM1','PM2A', 'PM5')) %>%
  group_by(Strain, Plate, Replicate, Group) %>%
  mutate(logAUC_C = logAUC_raw - logAUC_raw[Metabolite == 'Negative Control' & Type == 'Control']) %>% # Normalisation agains negative control in control
  ungroup %>%
  gather(Measure, Value, logAUC_C, logAUC_raw, logAUC) %>%
  group_by(Measure, Strain, Type, Plate, Well, Index, Metabolite, MetaboliteU) %>% #Work on subsets based on selected grouping variables
  summarise(Mean = mean(Value, na.rm = TRUE), #Do selected summary over group items - replicates, ignore missing values
            SD = sd(Value, na.rm = TRUE),
            SE = SD/sqrt(n())) %>%
  ungroup %>%
  mutate(PE = Mean + SE,
         NE = Mean - SE)




bac.sum.sbs = bac.sum %>% #Remove table grouping. Can be checked via glimpse(bac.sum)
  filter(Measure == 'logAUC_raw') %>%
  select(Strain, Type, Plate, Well, Index, Mean, SD) %>%
  #Transform the table wide to long, Mean and SD become values of a column named Value, while Mean and SD coding becomes Stat column values
  gather(Stat, Value, Mean, SD) %>% 
  unite(STS, Strain, Type, Stat) %>% # Generate unique IDs for summary columns based on Strain, Type and Stat - statistic values
  spread(STS, Value) # Spread the table to wide, showing statistics in each group


bacall = bac.byrep %>% 
  left_join(bac.sum.sbs) %>% 
  select(-c(Index, Metabolite, MetaboliteU)) %>% # Join with raw replicate data
  arrange(Plate, Col, Row) %>%
  select(-c('Row', 'Col'))


# Get timeseries data for the bacterial growth information
# It will take a while
data.b.ts = read_csv('../Bacteria data/All_files/Data_Leo5/Timeseries.csv',quote = "\"") %>%
  filter(Data == '750nm_f') %>% #Select only the relevant data to speed it up
  gather(Time_s, OD, matches('\\d')) %>%
  filter(!is.na(OD)) %>% #Remove empty values if there are missmatches
  mutate(Strain = as.character(Strain),
         Strain = recode(Strain,'BW25113'='BW'), #Change strain namings
         ReplicateB = paste0('B', as.character(Replicate)), #Generate replicate ID which indicate that it's data for bacteria
         Type = ifelse(Type == 'Control','C','T'),
         Type = factor(Type,
                     levels = c('C','T'),
                     labels = c('Control','Treatment')),
         Time_s = as.numeric(Time_s),
         Time_h = Time_s/3600,
         Row = str_match_all(Well,'[:digit:]{1,}'), #Get plate row names from well name. 
         Col = str_match_all(Well,'[:alpha:]{1,}'), #Get plate column names from well name
         Row = factor(Row, levels = 1:12), #Make them categorical variable with set order them
         Col = factor(Col, levels = LETTERS[1:8])) #Make them categorical variable with set order them


data.b.ts = data.b.ts %>% mutate(OD = as.numeric(OD))


# Growth curves for summary

tsum = data.b.ts %>%
  group_by(Strain, Type, Index, Plate, Well, Metabolite, MetaboliteU, Time_h) %>%
  summarise(Mean = mean(OD), SD = sd(OD),SE = SD/sqrt(length(OD))) %>%
  ungroup 


### load worm data


# Let's organise worm data
# Worm data
data.bw = read_xlsx('Biolog_worm/BW/BW_summary.xlsx', sheet = 'Summary')
data.crp = read_xlsx('../Worm_data/Biolog Worm nutrient screen - CRP.xlsx',sheet= 'All')
data.pyrE = read_xlsx('Biolog_worm/pyrE/pyrE_summary.xlsx',sheet = 'Summary')
data.TM = read_xlsx('Biolog_worm/udp udk upp/TM_summary.xlsx',sheet = 'Summary')

# Join all data, create scores, plates, experiments and worm replicate names

data.wa = rbind(data.bw, data.crp, data.pyrE, data.TM) %>%
  gather(Column, Worm_phenotype,`1`:`12`) %>%
  mutate(Score = as.numeric(ifelse(grepl('[0-9]', Worm_phenotype), as.numeric(Worm_phenotype), NA)),
         Plate = recode(Plate, 'PM2'='PM2A', 'PM3'='PM3B', 'PM4'='PM4A'),
         Replicate = as.character(Replicate),
         ReplicateW = paste0('W',Replicate),
         Experiment = paste0(ifelse(Type == 'Control', 'C','T'),`5FU_uM`)) %>%
  unite(Well, Row, Column, sep = '') %>%
  unite(SER, Strain, Experiment, ReplicateW, remove = FALSE) %>%
  left_join(info) %>%
  drop_na(Strain) %>%
  select(Strain, Type,`5FU_uM`, Experiment, Replicate, ReplicateW, SER, Plate, Well, Index:Class, Worm_phenotype, Score) 


### IMPORTANT DATA MODIFICATION:
  # everything lower or equal than 1 is going to be equal to 1

# data.wa[data.wa$Score <= 1 & !is.na(data.wa$Score),]$Score = 1
# data.wa[data.wa$Worm_phenotype <= 1 & !is.na(data.wa$Worm_phenotype),]$Worm_phenotype = 1


# Worm raw data side by side comparison
worm.byrep = data.wa %>%
  #left_join(info[,c('Plate','Well','MetaboliteU')]) %>%
  select(Plate, Well, Index, Metabolite, MetaboliteU, EcoCycID, KEGG_ID, SER, Score) %>%
  spread(SER, Score)
 

worm.sum = data.wa %>%
  group_by(Strain, Plate, Well, Experiment) %>%
  summarise(Median = median(Score, na.rm = TRUE),
            Mean = mean(Score, na.rm = TRUE),
            N = sum(!is.na(Score)),
            SD = sd(Score, na.rm = TRUE))
  

worm.sum.clean = worm.sum %>%
  gather(Stat, Value, Median:SD) %>%
  unite(SES, Strain, Experiment, Stat) %>%
  filter(!( SES == 'CRP_C0_SD' |
            SES == 'pyrE_C0_SD' 
            ) ) %>%
  select(Plate, Well, SES, Value) %>%
  spread(SES, Value)

## this creates a HUGE table with 64 variables 
wormall = worm.byrep %>%
  left_join(worm.sum.clean)


###
### PCA plots
###

# this big and dummy function will plot the PCA of the selected strains and save them in a PDF file
pca_plot = function(strain = "BW"){
  # filter by strain and Plate if you want
  pca_b_data = data.b %>%
    filter(Strain %in% c(strain) & Metabolite != 'Negative Control')

  # some data frame transformations
  pca_b_data = pca_b_data %>%
    select(SampleID, MetaboliteU, logAUC) %>%
    spread(MetaboliteU, logAUC) %>%
    data.frame(check.names = F)

  rownames(pca_b_data) = pca_b_data[,1]; pca_b_data = pca_b_data[,-1]

  # lets compute the PCA
  res.pca = PCA(pca_b_data, scale.unit = TRUE, ncp = 5, graph = F)

  # metadata 
  meta_var = bioinfo %>% filter(Strain %in% c(strain))

  # extract info about the individuals
  ind = get_pca_ind(res.pca)
  ind_df = data.frame(ind$coord[,1], ind$coord[,2], ind$coord[,3], meta_var$Type, 
    meta_var$Strain)

  colnames(ind_df) = c('Dim1', 'Dim2', 'Dim3', 'Type', 'Strain')

  # get ellipses based on the correlation
  getellipse = function(x, y, sc = 1) {
    as.data.frame(ellipse::ellipse(cor(x, y),
                                    scale = c(sd(x) * sc, sd(y) * sc),
                                    centre = c(mean(x), mean(y))))
  }

  # make a data frame from ellipses
  ell = ind_df %>% group_by(Type, Strain) %>% do(getellipse(.$Dim1, .$Dim2, 1)) %>% data.frame

  # plot!
  ggplot(ind_df, aes(x = Dim1, y = Dim2, color = Strain, group = interaction(Type, Strain))) + 
    geom_point(size = 3, show.legend = NA, alpha = 0.5) + 
    geom_path(data = ell, aes(x = x, y = y, group = interaction(Type, Strain), linetype = Type), size = 1) +
    geom_polygon(data = ell, aes(x = x, y = y, group = interaction(Type, Strain), 
      linetype = Type, fill = Strain), size = 1, alpha = 0.3) +
    xlab(paste("PC1 - ", round(res.pca$eig[1,2], 1), " % of variance", sep = "")) + 
    ylab(paste("PC2 - ", round(res.pca$eig[2,2], 1), " % of variance", sep = "")) +
    ggtitle(paste("PCA of strain:", unique(ell$Strain))) +
    theme(plot.title = element_text(hjust = 0.5),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank())

  # save the file
  ggsave(file = here('Summary',paste('PCA_', strain , '.pdf',sep = '')),
  width = 100, height = 80, units = 'mm', scale = 2, device = cairo_pdf, family = "Arial")
}

pca_plot("BW")
pca_plot("TM")
pca_plot("pyrE")
pca_plot(c("crp", "BW", "TM", "pyrE"))
# change name of generated file before next line
pca_plot("crp")



############################



###
### 4-way plot
###

# is a hell of a code, it's super messy, but it works...

worm.sum[worm.sum$Strain == 'CRP', ]$Strain = 'crp'
worm.sum$Strain = as.factor(worm.sum$Strain)



# print the list of variables 
for (name in unique(worm.sum$Strain)){
  print(name)
  print(unique((worm.sum %>% filter(Strain == name))$Experiment))
}

# select only one experiment and strain
# contrasts and other main variables of this part

strain = 'BW'
experiment = "T5"


str_C = paste(strain, '_C', sep = '')
str_T = paste(strain, '_T', sep = '')
str_CT = paste(strain, '_5FU', sep = '')
alln = paste(strain, '_5FU_Alln', sep = '')
adjs = paste(strain, '_5FU_adj', sep = '')


# for example, to mimic Pov's code
worm.sum %>% filter(Experiment == experiment, Strain == strain)

worm.old = worm.sum %>%
  filter(Experiment == experiment & Strain == strain) %>% 
  ungroup %>%
  mutate(Description = 'C. elegans development at 5uM 5-FU',
         Contrast = 'Ce_Dev5',   # C. elegans developement with 5FU
         Contrast_type = 'Treatment',
         FDR = NA) %>%
  select(Description, Contrast, Contrast_type, Plate, Well, logFC = Median, SE = SD, FDR)

# check that we filtered stuff properly
worm.old %>%
  group_by(Plate) %>%
  summarise(N = n())


# Join bacterial and worm results (change contrasts)
jointresults = allresults$results %>%
  filter((Contrast %in% c(str_C, str_T, str_CT, alln))) %>%
  mutate(Contrast = fct_recode(Contrast, adjs = alln)) %>% 
  select(Description, Contrast, Contrast_type, Plate, Well, logFC, SE, FDR) %>%
  bind_rows(worm.old) %>%
  left_join(info) %>%
  select(Description:Well,Index:KEGG_ID,logFC:FDR)


jointcast = jointresults %>%
  select(Contrast, Plate, Well, Index, Metabolite, MetaboliteU, EcoCycID, KEGG_ID, logFC, SE, FDR) %>%
  gather(Stat, Value, logFC, SE, FDR) %>%
  unite(CS, Contrast, Stat) %>%
  spread(CS, Value) %>%
  rename(Ce_Dev5_Median = Ce_Dev5_logFC, Ce_Dev5_SD = Ce_Dev5_SE) %>%
  select(-Ce_Dev5_FDR)


# write.csv(jointresults,paste(odir,'/Ecoli_results_All_As_old_screen.csv', sep = ''),row.names = FALSE)
# write.csv(jointcast,paste(odir,'/Ecoli_results_sidebyside_As_old_screen.csv', sep = ''),row.names = FALSE)

 
# Multiplex 
jointresults.multi = multiplex(jointresults,c("Plate","Well","Index","Metabolite","MetaboliteU","EcoCycID","KEGG_ID"))
jointresults.multi2 = multiplex(jointresults,c("Plate","Well","Index","Metabolite","MetaboliteU","EcoCycID","KEGG_ID"),2)




########################
NGMa = adjustments[adjustments$Contrast == alln, ]$a
NGMb = adjustments[adjustments$Contrast == alln, ]$b



gradcolours = c('#71B83B','yellow','orange','red')




total = jointresults.multi %>%
  filter(x_Contrast == str_C & y_Contrast == str_T & z_Contrast == 'Ce_Dev5')

first = jointresults.multi %>%
  filter(x_Contrast == str_C & y_Contrast == str_T & z_Contrast == 'Ce_Dev5') %>%
  filter(z_logFC <=1)

second = jointresults.multi %>%
  filter(x_Contrast == str_C & y_Contrast == str_T & z_Contrast == 'Ce_Dev5') %>%
  filter(z_logFC >1 & z_logFC <= 2)

third = jointresults.multi %>%
  filter(x_Contrast == str_C & y_Contrast == str_T & z_Contrast == 'Ce_Dev5') %>%
  filter(z_logFC >2 & z_logFC <= 3)

fourth = jointresults.multi %>%
  filter(x_Contrast == str_C & y_Contrast == str_T & z_Contrast == 'Ce_Dev5') %>%
  filter(z_logFC >3 & z_logFC <= 4)


ggplot(first, aes()) +
  geom_abline(intercept = 0, slope = 1, alpha = 0.3, color = 'grey', linetype = 'longdash') +
  geom_abline(aes(intercept = NGMb, slope = NGMa), alpha = 0.6, color = 'red') +
  geom_vline(aes(xintercept = 0), alpha = 0.9, color = 'grey') +
  geom_hline(aes(yintercept = 0), alpha = 0.9, color = 'grey') +
  geom_errorbarh(data = total, aes(y = y_logFC, xmax = x_logFC + x_SE, xmin = x_logFC - x_SE), height = 0, alpha = 0.3, color = 'grey50') +
  geom_errorbar(data = total, aes(x = x_logFC, ymax = y_logFC + y_SE, ymin = y_logFC - y_SE), width = 0, alpha = 0.3, color = 'grey50') +
  geom_point(aes(x = x_logFC, y = y_logFC, colour = z_logFC), alpha = 0.85, size = 2) +
  geom_point(data = second, aes(x = x_logFC, y = y_logFC, colour = z_logFC), alpha = 0.85, size = 2) +
  geom_point(data = third, aes(x = x_logFC, y = y_logFC, colour = z_logFC), alpha = 0.85, size = 2) +
  geom_point(data = fourth, aes(x = x_logFC, y = y_logFC, colour = z_logFC), alpha = 0.85, size = 2) +
  scale_size(range = c(1,5), name = 'C. elegans\nphenotype') +
  scale_colour_gradientn(colours = gradcolours,
                         breaks = c(1,2,3,4), limits = c(1,4), guide = "legend", name = 'C. elegans\nphenotype') +
  scale_y_continuous(breaks = -5:5)+
  coord_cartesian(xlim = c(-5, 2), ylim = c(-4, 4)) +
  labs(title = paste(strain, " growth with 5FU treatment at 5 uM", sep = ''),
  x = expression(paste(italic("E. coli"), ' growth vs NGM - Control, logFC', sep = '')), 
  y = expression(paste(italic('E. coli'), ' growth vs NGM - 5-FU Treatment, logFC', sep = ''))) +
  theme(plot.title = element_text(hjust = 0.5, face = "bold")) +
  geom_text_repel(data = fourth, aes(x = x_logFC, y = y_logFC, label = ifelse(z_logFC >= 4, MetaboliteU, '')), box.padding = unit(0.6, "lines"), segment.alpha = 0.4) + # only name those nutr with C. elegans phenotype 3 or more
  # geom_text_repel(aes(label = ifelse(z_logFC >= 3 | z_logFC == 0, MetaboliteU, '')), box.padding = unit(0.6, "lines"), segment.alpha = 0.4) + # only name those nutr with C. elegans phenotype 3 or more
  guides(color = guide_legend()) +
  theme(panel.grid.major = element_line(size = 0.06, colour = "grey50"),
      # panel.grid.major.y = element_blank(),
      panel.grid.minor.y = element_blank(),
      panel.background = element_rect(fill = "white", colour = "grey50"),
      legend.text = element_text(size = 15),
      legend.title = element_text(size = 15),
      axis.text.x = element_text(size = 10),
      axis.text.y = element_text(size = 10)) +
  guides(colour = guide_legend(override.aes = list(size = 4))) +
  annotate(geom = 'text', x = -2, y = 1.5, label = paste('y = ', round(NGMa,3), 'x +', round(NGMb,3), sep = ''), size = 5)


quartz.save(file = here('Summary', paste0("Scatter_", strain, "_5uM.pdf")),
	type = 'pdf', dpi = 300, height = 8, width = 10)


# scales for different mutants:
# BW: coord_cartesian(xlim = c(-5, 2), ylim = c(-4, 4))
# pyrE: coord_cartesian(xlim = c(-5, 2), ylim = c(-4, 4))
# TM: coord_cartesian(xlim = c(-4, 2), ylim = c(-4, 2.5))








####
# linear modeling, statistical analyses



contrasts = read.contrasts('!Contrasts.xlsx') # This table describes comparisons made in data

# loads the metadata table
contrasts.table = contrasts$Contrasts.table
# loads the contrasts matrix (1s and 0s)
contr.matrix = contrasts$Contrasts.matrix

# shortens the metadata data frame
contr.desc = contrasts.table %>%
  select(Description:Strain)



# Initialise adjustments
group = c('All','PM4A','PM3B','PM2A','PM1')
strain = c('BW','TM','crp','pyrE')


adjustments = expand.grid('Group' = group, 'Strain' = strain) %>%
  mutate(a = -1, b = 0,
         Contrast = paste0(Strain, '_5FU_', Group, 'n')) %>%
  select(Contrast, Group:b) 



# transform the contr.matrix into a real matrix (not data frame)
contr.matrix = contr.matrix %>%
  as.matrix()


# this piece of code performs a lot of different things, be careful

allresults = data.b %>%
  #filter(Strain == 'BW') %>%
  filter(!Metabolite %in% c('Negative Control','Positive Control') ) %>%
  # filter(! (Plate == 'PM3B' & SampleID == 'BW_C_1') ) %>%
  # filter(! (Plate == 'PM4A' & SampleID == 'TM_C_3') ) %>%
  group_by(Plate, Well, Index, Metabolite, MetaboliteU, EcoCycID, KEGG_ID) %>%
  # Another creation of mine. Nothing fancy, just a wrapper for the use of contrasts in LM. 
  # But integrates nicely with tidyverse workflow. Code in PFun
  do(hypothesise(.,"logAUC~0+Sample", contr.matrix)) %>% 
  group_by(Plate, Well, Metabolite, MetaboliteU, EcoCycID, KEGG_ID) %>%
  getresults(contr.desc) # Calculate some additional parameters. Code in PFun

#get results in different shapes
results = allresults$results
results.cast = allresults$cast
results.castfull = allresults$castfull


results.cor = multiplex(results,c("Strain", "Plate", "Well", "Index", "Metabolite", "MetaboliteU", "EcoCycID", "KEGG_ID"), 2) %>% 
  filter(str_detect(x_Contrast,'_C') &
           str_detect(y_Contrast,'_T'))

# Step No 2
# Find contrast adjustments
confounding = function(adjustments, data) {
  
  grp = as.character(adjustments$Group)
  strn <= as.character(adjustments$Strain)


  print(paste0("Strain: ",strn) )
  print(paste0("Group: ",grp) )
  
  seldata=data %>%
    filter(Strain==strn)
  
  if (grp=='All'){
    seldata=seldata
  } else if (grp=='PM1'){
    seldata=seldata %>%
      filter(Plate %in% c('PM1'))
  } else if (grp=='PM3B') {
    seldata=seldata %>%
      filter(Plate %in% c('PM3B'))
  } else if (grp=='PM4A') {
    seldata=seldata %>%
      filter(Plate %in% c('PM4A'))
  } else if (grp=='PM2A') {
    seldata=seldata %>%
      filter(Plate %in% c('PM2A'))
  } 

  print(paste0('Plates: ', paste0(seldata$Plate %>% unique %>% print,collapse=';') ) )
  print(paste0('Rows: ',dim(seldata)[1]) )
  
  
  if (dim(seldata)[1] == 0){
    result=data.frame('a' = NA,
                       'neg_a' = NA,
                       'b' = NA,
                       'a_p' = NA,
                       'b_p' = NA,
                       'r2' = NA)
    return(result)
  }

  print('First round')
  
  # print(unique(seldata$x_Contrast))
  # print(unique(seldata$y_Contrast))
  
  # frml=paste0(strn,"_T_logFC~",strn,"_C_logFC")
  # print(paste0("Formula: ",frml) )
  
  #genfit=lm(seldata[,paste0(strn,"_T_logFC")]~seldata[,paste0(strn,"_C_logFC")])
  
  #attach(seldata)
  attach(seldata)
  genfit = lm("y_logFC~x_logFC")
  
  genres = summary(genfit)
  
  car::outlierTest(genfit) # Automatically remove outliers, which could skew the correlation. Especially valuable in the case of 5-FU
  ot = car::outlierTest(genfit)
  car::qqPlot(genfit, main = "QQ Plot")
  outlist=c(names(ot$rstudent))
  #Outliers:
  print(paste('Outliers in ', grp, sep = ''))
  print(seldata[outlist,])
  #
  #
  filtseldata = seldata[setdiff(rownames(seldata),outlist),]
  
  detach(seldata)

  print('Second round')
  # 
  #Get final fit
  attach(filtseldata)
  genfit2 = lm("y_logFC~x_logFC")
  genres = summary(genfit2)
  
  result = data.frame('a' = genres$coefficients[[2]],
                     'neg_a' = -genres$coefficients[[2]],
                     'b' = genres$coefficients[[1]],
                     'a_p' = genres$coefficients[[8]],
                     'b_p' = genres$coefficients[[7]],
                     'r2' = genres$r.squared)
  

  return(result)

}



# Update adjustments based on identified correlations. Go back to line 806 and rerun linear modeling with adjustments
adjustments = adjustments %>%
  group_by(Contrast,Group,Strain) %>%
  do(confounding(adjustments = ., data = results.cor)) #



# Update this based on identified adjustment values
# Only run this after the first round of analysis
#######################################


contr.matrix = contr.matrix %>%
  data.frame()


contr.matrix['BW_5FU_Alln',c('BW_C','m')] = adjustments[adjustments$Contrast ==  'BW_5FU_Alln', c('neg_a','b')]
contr.matrix['TM_5FU_Alln',c('TM_C','m')] = adjustments[adjustments$Contrast ==  'TM_5FU_Alln', c('neg_a','b')]
contr.matrix['crp_5FU_Alln',c('crp_C','m')] = adjustments[adjustments$Contrast == 'crp_5FU_Alln', c('neg_a','b')]
contr.matrix['pyrE_5FU_Alln',c('pyrE_C','m')]  = adjustments[adjustments$Contrast == 'pyrE_5FU_Alln', c('neg_a','b')]


#######################################


#### new round of statistical analyses
contr.matrix = contr.matrix %>%
  as.matrix()
# this piece of code performs a lot of different things, be careful

allresults = data.b %>%
  #filter(Strain == 'BW') %>%
  filter(!Metabolite %in% c('Negative Control','Positive Control') ) %>%
  # filter(! (Plate == 'PM3B' & SampleID == 'BW_C_1') ) %>%
  # filter(! (Plate == 'PM4A' & SampleID == 'TM_C_3') ) %>%
  group_by(Plate, Well, Index, Metabolite, MetaboliteU, EcoCycID, KEGG_ID) %>%
  # Another creation of mine. Nothing fancy, just a wrapper for the use of contrasts in LM. 
  # But integrates nicely with tidyverse workflow. Code in PFun
  do(hypothesise(.,"logAUC~0+Sample", contr.matrix)) %>% 
  group_by(Plate, Well, Metabolite, MetaboliteU, EcoCycID, KEGG_ID) %>%
  getresults(contr.desc) # Calculate some additional parameters. Code in PFun



#get results in different shapes
results = allresults$results
results.cast = allresults$cast
results.castfull = allresults$castfull


# Save statistical analysis results

list_of_datasets = list('results' = results, 'results.cast' = results.cast, "results.castfull" = results.castfull)

write.xlsx(list_of_datasets, here('Summary', 'stats.xlsx'), colNames = T, rowNames = F) 

















